"""Ré-exports de haut niveau exposés à la racine du package."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_init.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/99_init.ipynb #e39c73eb
"""Tools to graft classifiers onto an adversarial autoencoder."""

__version__ = "0.0.1"

from .adapters import AAEAdapter, GraftedAAEClassifier, freeze_module
from .callbacks import CollectLatentSpaceCallback
from .config import FastaiLatentResult, HumanCenteredAAEConfig, HumanCenteredFeatures, LatentBatch
from .features import extract_human_aae_features
from .graft import graft_classifier_to_human_aae, infer_out_features, make_grafted_learner
from .latent import collect_latents, extract_latents_from_learner
from tell_me_why.plots import (
    plot_feature_distributions,
    plot_feature_grid,
    plot_latent_gaussian,
)
from tell_me_why.source import (
    HUMAN_CENTERED_XAI_BRANCH,
    HUMAN_CENTERED_XAI_REPO_URL,
    build_human_centered_aae,
    ensure_human_centered_xai_repo,
    load_human_centered_aae_module,
    resolve_human_centered_aae_path,
)

__all__ = [
    "AAEAdapter",
    "CollectLatentSpaceCallback",
    "GraftedAAEClassifier",
    "FastaiLatentResult",
    "HUMAN_CENTERED_XAI_BRANCH",
    "HUMAN_CENTERED_XAI_REPO_URL",
    "HumanCenteredAAEConfig",
    "HumanCenteredFeatures",
    "LatentBatch",
    "build_human_centered_aae",
    "collect_latents",
    "ensure_human_centered_xai_repo",
    "extract_human_aae_features",
    "extract_latents_from_learner",
    "freeze_module",
    "graft_classifier_to_human_aae",
    "infer_out_features",
    "load_human_centered_aae_module",
    "make_grafted_learner",
    "plot_feature_distributions",
    "plot_feature_grid",
    "plot_latent_gaussian",
    "resolve_human_centered_aae_path",
]

