"""This notebook generates `tell_me_why/__init__.py`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_init.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_init.ipynb #54aff831
__version__ = "0.0.2"
