"""Dataclasses simples partagées par les autres modules."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_config.ipynb.

# %% auto #0
__all__ = ['HumanCenteredAAEConfig', 'FastaiLatentResult', 'HumanCenteredFeatures', 'LatentBatch']

# %% ../nbs/01_config.ipynb #0cedf5d1
"""Small data objects shared across the library."""


from dataclasses import asdict, dataclass
from typing import Any

from torch import Tensor


@dataclass
class HumanCenteredAAEConfig:
    """Constructor arguments used by `modelAAE_DROPOUT.AAE`."""

    input_size: int = 256
    input_channels: int = 3
    encoding_dims: int = 128
    classes: int = 2
    gen_train: bool = True
    skip_dropout: float = 1.0

    def to_kwargs(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class FastaiLatentResult:
    """Latents and predictions extracted from a fastai `Learner`."""

    latents: Tensor
    preds: Tensor | None = None
    targets: Tensor | None = None
    vocab: Any | None = None


@dataclass
class HumanCenteredFeatures:
    """Feature tensors exposed by the Human-Centered AAE."""

    logits: Tensor
    latents: Tensor
    encoder_features: Tensor
    reconstruction: Tensor | None = None


@dataclass
class LatentBatch:
    """Latent vectors collected from a generic PyTorch dataloader."""

    latents: Tensor
    labels: Tensor | None = None

    def numpy(self) -> tuple[Any, Any | None]:
        """Return `(latents, labels)` as NumPy arrays."""

        labels = None if self.labels is None else self.labels.numpy()
        return self.latents.numpy(), labels

