"""Façade de compatibilité pour les anciens imports `tell_me_why.core`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/90_core_compat.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/90_core_compat.ipynb #06780524
"""Backward-compatible imports for the old `tell_me_why.core` module."""

from .adapters import AAEAdapter, GraftedAAEClassifier, freeze_module
from .config import LatentBatch
from .latent import collect_latents, default_input_getter, default_target_getter

__all__ = [
    "AAEAdapter",
    "GraftedAAEClassifier",
    "LatentBatch",
    "collect_latents",
    "default_input_getter",
    "default_target_getter",
    "freeze_module",
]

