"""Façade de compatibilité pour les anciens imports `tell_me_why.fastai_aae`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/91_fastai_aae_compat.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/91_fastai_aae_compat.ipynb #14aad8ab
"""Backward-compatible imports for the old `tell_me_why.fastai_aae` module."""

from .callbacks import CollectLatentSpaceCallback, as_fastai_callback
from .config import FastaiLatentResult, HumanCenteredAAEConfig, HumanCenteredFeatures
from .features import extract_human_aae_features
from .graft import graft_classifier_to_human_aae, infer_out_features, make_grafted_learner
from .latent import extract_latents_from_learner
from tell_me_why.source import (
    DEFAULT_HUMAN_CENTERED_XAI_MODEL,
    DEFAULT_HUMAN_CENTERED_XAI_REPO,
    HUMAN_CENTERED_XAI_BRANCH,
    HUMAN_CENTERED_XAI_MODEL_FILE,
    HUMAN_CENTERED_XAI_REPO_URL,
    build_human_centered_aae,
    ensure_human_centered_xai_repo,
    load_human_centered_aae_module,
    resolve_human_centered_aae_path,
)

_as_fastai_callback = as_fastai_callback

__all__ = [
    "CollectLatentSpaceCallback",
    "DEFAULT_HUMAN_CENTERED_XAI_MODEL",
    "DEFAULT_HUMAN_CENTERED_XAI_REPO",
    "FastaiLatentResult",
    "HUMAN_CENTERED_XAI_BRANCH",
    "HUMAN_CENTERED_XAI_MODEL_FILE",
    "HUMAN_CENTERED_XAI_REPO_URL",
    "HumanCenteredAAEConfig",
    "HumanCenteredFeatures",
    "_as_fastai_callback",
    "as_fastai_callback",
    "build_human_centered_aae",
    "ensure_human_centered_xai_repo",
    "extract_human_aae_features",
    "extract_latents_from_learner",
    "graft_classifier_to_human_aae",
    "infer_out_features",
    "load_human_centered_aae_module",
    "make_grafted_learner",
    "resolve_human_centered_aae_path",
]

