"""Utility functions for mapping fastai learner outputs and computing interpretable scores on images."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_feature_scores.ipynb.

# %% ../nbs/02_feature_scores.ipynb #3d6ad948
from __future__ import annotations

import math
from collections.abc import Callable, Iterable, Sequence
from pathlib import Path
from typing import Any, Literal

import torch
import torch.fft
from torch import Tensor
from torchvision.io import ImageReadMode, read_image
import torchvision.transforms.functional as TF

try:
    from tqdm.auto import tqdm
except ModuleNotFoundError:  # pragma: no cover - fallback for minimal environments
    def tqdm(iterable=None, *args, **kwargs):
        return iterable if iterable is not None else []

ErrorPolicy = Literal["previous", "nan", "raise"]
ImagePath = str | Path
ScoreFn = Callable[[Sequence[ImagePath]], list[float]]


def _as_paths(image_paths: Iterable[ImagePath]) -> list[Path]:
    return [Path(path) for path in image_paths]


def _read_grayscale_image(image_path: ImagePath, image_size: tuple[int, int] | None = None) -> Tensor:
    img = read_image(str(image_path), mode=ImageReadMode.GRAY).float() / 255.0
    if image_size is not None:
        img = TF.resize(img, list(image_size), antialias=True)
    if img.shape[0] > 1:
        img = TF.rgb_to_grayscale(img[:3])
    return img


def _read_rgb_image(image_path: ImagePath, image_size: tuple[int, int] | None = None) -> Tensor:
    img = read_image(str(image_path), mode=ImageReadMode.RGB).float() / 255.0
    if image_size is not None:
        img = TF.resize(img, list(image_size), antialias=True)
    return img


def _handle_score_error(error: Exception, image_path: Path, last_valid_score: float, on_error: ErrorPolicy) -> float:
    if on_error == "raise":
        raise error
    if on_error == "nan":
        return float("nan")
    if on_error == "previous":
        print(f"Error for {image_path}: {error} -> assigning previous score: {last_valid_score:.4f}")
        return last_valid_score
    raise ValueError(f"Unknown error policy: {on_error!r}")


def _compute_scores(
    image_paths: Iterable[ImagePath],
    scorer: Callable[[Path], float],
    desc: str,
    on_error: ErrorPolicy = "previous",
) -> list[float]:
    scores: list[float] = []
    last_valid_score = 0.0

    for image_path in tqdm(_as_paths(image_paths), desc=desc):
        try:
            score = float(scorer(image_path))
            if not math.isfinite(score):
                raise ValueError(f"Non-finite score: {score}")
            scores.append(score)
            last_valid_score = score
        except Exception as error:
            scores.append(_handle_score_error(error, image_path, last_valid_score, on_error))

    return scores


def _require_pandas():
    try:
        import pandas as pd
    except ModuleNotFoundError as error:  # pragma: no cover - environment dependent
        raise ModuleNotFoundError("pandas is required for tabular feature-score outputs") from error
    return pd

# %% auto #0
__all__ = ['ErrorPolicy', 'ImagePath', 'ScoreFn', 'mapping', 'FEATURE_SCORE_CATEGORIES', 'map_learner_predictions',
           'compute_brightness_scores', 'compute_variance_scores', 'compute_skewness_scores',
           'compute_color_covariance_scores', 'compute_redness_dominance_scores', 'compute_symmetry_scores',
           'compute_top_bottom_ratio_scores', 'compute_center_texture_scores', 'compute_eye_region_contrast_scores',
           'compute_jaw_texture_scores', 'compute_fft_scores', 'find_otsu_threshold', 'available_feature_scores',
           'compute_feature_score_table']

# %% ../nbs/02_feature_scores.ipynb #a8c8a76c
def _class_indices(values: Tensor) -> Tensor:
    if values.ndim > 1:
        return values.argmax(dim=-1)
    return values


def _class_names(indices: Tensor, vocab: Any) -> list[str] | None:
    if vocab is None:
        return None
    return [str(vocab[int(idx)]) for idx in indices]


def map_learner_predictions(
    learn: Any,
    ds_idxs: Sequence[int] = (0, 1),
    include_predictions: bool = False,
):
    """Map fastai learner predictions back to their source files.

    Parameters
    ----------
    learn : fastai Learner
        Learner whose dataloaders expose the original dataset items.
    ds_idxs : sequence of int, default=(0, 1)
        Dataset indices to map. In fastai, 0 is usually train and 1 is valid.
    include_predictions : bool, default=False
        When True, append target and prediction columns to the provenance table.

    Returns
    -------
    tuple[Tensor, pandas.DataFrame]
        Concatenated inputs and a DataFrame aligned row-by-row with these inputs.
    """
    pd = _require_pandas()
    all_inputs: list[Tensor] = []
    all_dfs = []
    vocab = getattr(learn.dls, "vocab", None)

    for ds_idx in ds_idxs:
        inputs, preds, targets = learn.get_preds(ds_idx=ds_idx, with_input=True, reorder=False)
        dl = learn.dls[ds_idx]
        indices = list(dl.get_idxs())
        original_files = list(dl.dataset.items)
        path_mapping = [original_files[idx] for idx in indices]

        set_name = "Train" if ds_idx == 0 else "Valid" if ds_idx == 1 else f"Dataset {ds_idx}"
        mapping_df = pd.DataFrame(
            {
                "Set": set_name,
                "Original_Dataset_Index": indices,
                "Source_File_Path": [str(path) for path in path_mapping],
            }
        )

        if include_predictions:
            predicted_class_indices = _class_indices(preds).cpu()
            real_target_indices = _class_indices(targets).cpu()
            predicted_class_names = _class_names(predicted_class_indices, vocab)
            mapping_df["Real_Target_ID"] = real_target_indices.numpy()
            mapping_df["Predicted_Class_ID"] = predicted_class_indices.numpy()
            if predicted_class_names is not None:
                mapping_df["Predicted_Class_Name"] = predicted_class_names
            mapping_df["Correct_Prediction"] = (
                real_target_indices.numpy() == predicted_class_indices.numpy()
            )

        all_inputs.append(inputs)
        all_dfs.append(mapping_df)

    return torch.cat(all_inputs, dim=0), pd.concat(all_dfs, ignore_index=True)


# Backward-compatible alias for the original helper name.
mapping = map_learner_predictions

# %% ../nbs/02_feature_scores.ipynb #49fa97e5
def compute_brightness_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute mean grayscale intensity for each image."""
    return _compute_scores(
        image_paths,
        lambda path: _read_grayscale_image(path).mean().item(),
        desc="Computing brightness",
        on_error=on_error,
    )


def compute_variance_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute grayscale variance as a global contrast score."""
    return _compute_scores(
        image_paths,
        lambda path: _read_grayscale_image(path).var().item(),
        desc="Computing variance / contrast",
        on_error=on_error,
    )


def compute_skewness_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute grayscale skewness for each image."""
    def scorer(path: Path) -> float:
        img = _read_grayscale_image(path)
        mean = img.mean()
        std = img.std()
        if std <= 1e-6:
            return 0.0
        return (((img - mean) ** 3).mean() / (std**3)).item()

    return _compute_scores(image_paths, scorer, desc="Computing skewness", on_error=on_error)

# %% ../nbs/02_feature_scores.ipynb #21df3d09
def compute_color_covariance_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute covariance between red and blue channels."""
    def scorer(path: Path) -> float:
        img = _read_rgb_image(path)
        red_channel = img[0].flatten()
        blue_channel = img[2].flatten()
        cov_matrix = torch.cov(torch.stack([red_channel, blue_channel]))
        return cov_matrix[0, 1].item()

    return _compute_scores(image_paths, scorer, desc="Computing red/blue covariance", on_error=on_error)


def compute_redness_dominance_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute red-channel dominance relative to green and blue channels."""
    def scorer(path: Path) -> float:
        img = _read_rgb_image(path)
        red_mean = img[0].mean()
        green_mean = img[1].mean()
        blue_mean = img[2].mean()
        return (red_mean / (green_mean + blue_mean + 1e-6)).item()

    return _compute_scores(image_paths, scorer, desc="Computing red dominance", on_error=on_error)

# %% ../nbs/02_feature_scores.ipynb #da603a2c
def compute_symmetry_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute horizontal symmetry error. Lower values mean stronger symmetry."""
    def scorer(path: Path) -> float:
        img = _read_grayscale_image(path)
        img_flipped = torch.flip(img, dims=[2])
        return torch.abs(img - img_flipped).mean().item()

    return _compute_scores(image_paths, scorer, desc="Computing symmetry", on_error=on_error)


def compute_top_bottom_ratio_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute mean brightness ratio between upper and lower halves."""
    def scorer(path: Path) -> float:
        img = _read_grayscale_image(path)
        h = img.shape[1]
        top_half = img[:, : h // 2, :].mean()
        bottom_half = img[:, h // 2 :, :].mean()
        return (top_half / (bottom_half + 1e-6)).item()

    return _compute_scores(image_paths, scorer, desc="Computing top/bottom ratio", on_error=on_error)


def compute_center_texture_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute grayscale variance in the central crop of each image."""
    def scorer(path: Path) -> float:
        img = _read_grayscale_image(path)
        h, w = img.shape[1], img.shape[2]
        center_region = img[:, h // 4 : 3 * h // 4, w // 4 : 3 * w // 4]
        return center_region.var().item()

    return _compute_scores(image_paths, scorer, desc="Computing central texture", on_error=on_error)


def compute_eye_region_contrast_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute grayscale variance in a horizontal band roughly matching the eye region."""
    def scorer(path: Path) -> float:
        img = _read_grayscale_image(path)
        h = img.shape[1]
        eye_region = img[:, int(h * 0.3) : int(h * 0.5), :]
        return eye_region.var().item()

    return _compute_scores(image_paths, scorer, desc="Computing eye contrast", on_error=on_error)


def compute_jaw_texture_scores(image_paths: Iterable[ImagePath], on_error: ErrorPolicy = "previous") -> list[float]:
    """Compute lower-face edge activity from adjacent-pixel intensity differences."""
    def scorer(path: Path) -> float:
        img = _read_grayscale_image(path)
        h = img.shape[1]
        jaw_region = img[:, int(h * 0.7) :, :]
        diff_x = torch.abs(jaw_region[:, :, 1:] - jaw_region[:, :, :-1]).mean()
        diff_y = torch.abs(jaw_region[:, 1:, :] - jaw_region[:, :-1, :]).mean()
        return (diff_x + diff_y).item()

    return _compute_scores(image_paths, scorer, desc="Computing jaw texture", on_error=on_error)

# %% ../nbs/02_feature_scores.ipynb #2b0c99cb
def compute_fft_scores(
    image_paths: Iterable[ImagePath],
    radius: int = 30,
    image_size: tuple[int, int] = (200, 200),
    on_error: ErrorPolicy = "previous",
) -> list[float]:
    """Compute the high-frequency energy ratio for each image.

    The central disk of radius `radius` is treated as low frequency. The score is
    the remaining high-frequency energy divided by total FFT magnitude energy.
    """
    def scorer(path: Path) -> float:
        img = _read_grayscale_image(path, image_size=image_size)
        if img.ndim == 3:
            if img.shape[0] > 1:
                img = TF.rgb_to_grayscale(img[:3])
            img = img.squeeze(0)
        else:
            img = img.squeeze()
        if img.ndim != 2:
            raise ValueError(f"Expected a 2D grayscale image for FFT, got shape {tuple(img.shape)}")

        fshift = torch.fft.fftshift(torch.fft.fft2(img))
        magnitude_spectrum = torch.abs(fshift)

        rows, cols = img.shape
        crow, ccol = rows // 2, cols // 2
        y = torch.arange(-crow, rows - crow, device=img.device).view(-1, 1)
        x = torch.arange(-ccol, cols - ccol, device=img.device).view(1, -1)
        low_frequency_mask = x**2 + y**2 <= radius**2

        total_energy = magnitude_spectrum.sum()
        if total_energy <= 0:
            return 0.0
        low_frequency_energy = magnitude_spectrum[low_frequency_mask].sum()
        high_frequency_energy = total_energy - low_frequency_energy
        return (high_frequency_energy / total_energy).item()

    return _compute_scores(image_paths, scorer, desc="Computing FFT scores", on_error=on_error)


def find_otsu_threshold(im_gray: Tensor) -> int:
    """Find Otsu's threshold for a grayscale image tensor.

    Accepts images scaled either in `[0, 1]` or `[0, 255]`.
    """
    img = im_gray.detach().float()
    if img.numel() == 0:
        return 0
    if img.max() <= 1:
        img = img * 255
    img = img.clamp(0, 255)

    hist = torch.histc(img, bins=256, min=0, max=255)
    if hist.sum() <= 0:
        return 0
    p = hist / hist.sum()
    intensities = torch.arange(256, dtype=torch.float32, device=img.device)

    max_sigma_b = torch.tensor(0.0, device=img.device)
    optimal_threshold = 0
    for threshold in range(1, 255):
        w0 = p[:threshold].sum()
        w1 = p[threshold:].sum()
        if w0 == 0 or w1 == 0:
            continue
        mu0 = (intensities[:threshold] * p[:threshold]).sum() / w0
        mu1 = (intensities[threshold:] * p[threshold:]).sum() / w1
        sigma_b = w0 * w1 * (mu0 - mu1) ** 2
        if sigma_b > max_sigma_b:
            max_sigma_b = sigma_b
            optimal_threshold = threshold

    return optimal_threshold

# %% ../nbs/02_feature_scores.ipynb #94337678
FEATURE_SCORE_CATEGORIES: dict[str, dict[str, ScoreFn]] = {
    "intensity": {
        "brightness": compute_brightness_scores,
        "variance": compute_variance_scores,
        "skewness": compute_skewness_scores,
    },
    "color": {
        "color_covariance_red_blue": compute_color_covariance_scores,
        "redness_dominance": compute_redness_dominance_scores,
    },
    "spatial": {
        "symmetry_error": compute_symmetry_scores,
        "top_bottom_brightness_ratio": compute_top_bottom_ratio_scores,
        "center_texture": compute_center_texture_scores,
        "eye_region_contrast": compute_eye_region_contrast_scores,
        "jaw_texture": compute_jaw_texture_scores,
    },
    "frequency": {
        "fft_high_frequency_ratio": compute_fft_scores,
    },
}


def available_feature_scores() -> dict[str, list[str]]:
    """Return available feature-score names grouped by category."""
    return {category: list(scores) for category, scores in FEATURE_SCORE_CATEGORIES.items()}


def _flatten_feature_scores() -> dict[str, ScoreFn]:
    return {
        score_name: score_fn
        for category_scores in FEATURE_SCORE_CATEGORIES.values()
        for score_name, score_fn in category_scores.items()
    }


def compute_feature_score_table(
    image_paths: Iterable[ImagePath],
    score_names: Sequence[str] | None = None,
    on_error: ErrorPolicy = "previous",
):
    """Compute selected feature scores and return them in a pandas DataFrame.

    Parameters
    ----------
    image_paths : iterable of str or Path
        Images to score.
    score_names : sequence of str, optional
        Names from `available_feature_scores()`. When omitted, all scores are computed.
    on_error : {"previous", "nan", "raise"}, default="previous"
        Error handling policy for unreadable images.
    """
    pd = _require_pandas()
    paths = _as_paths(image_paths)
    flat_scores = _flatten_feature_scores()
    selected_names = list(flat_scores) if score_names is None else list(score_names)

    unknown_scores = sorted(set(selected_names) - set(flat_scores))
    if unknown_scores:
        raise KeyError(f"Unknown feature scores: {unknown_scores}")

    data: dict[str, Any] = {"Source_File_Path": [str(path) for path in paths]}
    for score_name in selected_names:
        data[score_name] = flat_scores[score_name](paths, on_error=on_error)

    return pd.DataFrame(data)
