"""Attach xAAEnet explanation blocks to a user-provided encoder."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_graft_classifier.ipynb.

# %% auto #0
__all__ = ['set_module_trainable', 'EncoderGraftedAAE', 'graft_xaae_encoder']

# %% ../nbs/03_graft_classifier.ipynb #f689aa4f
from collections.abc import Callable

import torch
import torch.nn as nn
import torch.nn.functional as F
from fastai.torch_core import TensorBase
from torch import Tensor

from .model_aae import DynamicUnetSkipDropout


def set_module_trainable(module: nn.Module, trainable: bool) -> nn.Module:
    """Enable or disable gradient updates for every parameter in a module."""
    for parameter in module.parameters():
        parameter.requires_grad = trainable
    return module


def _module_device(module: nn.Module) -> torch.device:
    try:
        return next(module.parameters()).device
    except StopIteration:
        return torch.device("cpu")


class EncoderGraftedAAE(nn.Module):
    """xAAEnet model built from a user-provided encoder.

    The user encoder replaces the default ResNet encoder used by `AAE`.
    `DynamicUnetSkipDropout` then builds the symmetric U-Net decoder from this
    encoder and its skip connections.
    """

    def __init__(
        self,
        encoder: nn.Module,
        input_size: int = 256,
        input_channels: int = 3,
        encoding_dims: int = 128,
        severity_outputs: int = 1,
        severity_head: nn.Module | None = None,
        gen_train: bool = True,
        skip_dropout: float = 1.0,
        freeze_encoder: bool = False,
    ):
        super().__init__()
        self.gen_train = gen_train
        self.input_size = input_size
        self.input_channels = input_channels
        self.encoding_dims = encoding_dims
        self.severity_outputs = severity_outputs

        if freeze_encoder:
            set_module_trainable(encoder, False)

        self.unet = DynamicUnetSkipDropout(
            encoder=encoder,
            n_out=input_channels,
            img_size=(input_size, input_size),
            skip_dropout=skip_dropout,
            last_cross=False,
        )

        self.flatten = nn.Flatten()
        self.encoder_feature_shape = self._infer_encoder_feature_shape()
        flat_features = int(torch.tensor(self.encoder_feature_shape).prod().item())

        self.fc_encode = nn.Linear(flat_features, encoding_dims)
        self.bn_lin = nn.BatchNorm1d(num_features=encoding_dims)
        self.decoder_fc = nn.Linear(encoding_dims, flat_features)
        self.severity_head = severity_head if severity_head is not None else nn.Linear(encoding_dims, severity_outputs)

        self.fc_crit1 = nn.Linear(encoding_dims, 64)
        self.fc_crit2 = nn.Linear(64, 16)
        self.fc_crit3 = nn.Linear(16, 1)
        self.bn_crit1 = nn.BatchNorm1d(num_features=64)
        self.bn_crit2 = nn.BatchNorm1d(num_features=16)

    def _infer_encoder_feature_shape(self) -> tuple[int, ...]:
        encoder = self.unet.layers[0]
        was_training = encoder.training
        device = _module_device(encoder)
        try:
            encoder.eval()
            with torch.no_grad():
                sample = torch.zeros(1, self.input_channels, self.input_size, self.input_size, device=device)
                features = encoder(sample)
        finally:
            encoder.train(was_training)
        return tuple(features.shape[1:])

    def latent_gan(self, z: Tensor) -> Tensor:
        x = F.leaky_relu(self.bn_crit1(self.fc_crit1(z)), negative_slope=0.2)
        x = F.leaky_relu(self.bn_crit2(self.fc_crit2(x)), negative_slope=0.2)
        return torch.sigmoid(self.fc_crit3(x))

    def reconstruction_loss(self, loss_func: Callable[[Tensor, Tensor], Tensor] | None = None) -> Tensor:
        reconstruction_loss_func = loss_func if loss_func is not None else F.mse_loss
        return reconstruction_loss_func(self.decoder_output, self.input_image)

    def severity_loss_func(
        self,
        output: Tensor,
        target: Tensor,
        RECONS_WEIGHT: float = 0.0,
        SEVERITY_WEIGHT: float = 1.0,
        user_loss_func: Callable[..., Tensor] | None = None,
        reconstruction_loss_func: Callable[[Tensor, Tensor], Tensor] | None = None,
        **kwargs,
    ) -> Tensor:
        score_loss_func = user_loss_func if user_loss_func is not None else F.mse_loss
        self.severity_loss = score_loss_func(output, target, **kwargs)
        self.recons_loss = self.reconstruction_loss(reconstruction_loss_func)
        return SEVERITY_WEIGHT * self.severity_loss + RECONS_WEIGHT * self.recons_loss

    def aae_loss_func(
        self,
        output: Tensor,
        target: Tensor,
        RECONS_WEIGHT: float = 0.0,
        SEVERITY_WEIGHT: float = 1.0,
        ADV_WEIGHT: float = 1.0,
        user_loss_func: Callable[..., Tensor] | None = None,
        reconstruction_loss_func: Callable[[Tensor, Tensor], Tensor] | None = None,
        **kwargs,
    ) -> Tensor:
        adversarial_loss = nn.BCELoss()

        if self.gen_train:
            valid = torch.ones_like(self.gan_fake, requires_grad=False).detach()
            self.adv_loss = adversarial_loss(self.gan_fake, valid)
            self.crit_loss = output.new_zeros(())
        else:
            valid = torch.ones_like(self.gan_real, requires_grad=False).detach()
            fake = torch.zeros_like(self.gan_fake, requires_grad=False).detach()
            self.real_loss = adversarial_loss(self.gan_real, valid)
            self.fake_loss = adversarial_loss(self.gan_fake, fake)
            self.adv_loss = 0.6 * self.real_loss + 0.4 * self.fake_loss
            self.crit_loss = self.adv_loss

        score_loss_func = user_loss_func if user_loss_func is not None else F.mse_loss
        self.severity_loss = score_loss_func(output, target, **kwargs)
        self.recons_loss = self.reconstruction_loss(reconstruction_loss_func)

        return (
            ADV_WEIGHT * self.adv_loss
            + SEVERITY_WEIGHT * self.severity_loss
            + RECONS_WEIGHT * self.recons_loss
        )

    def forward(self, x: Tensor) -> Tensor:
        self.input_image = x

        feats = self.unet.layers[0](x)
        flat = self.flatten(feats)
        self.z = F.leaky_relu(self.bn_lin(self.fc_encode(flat)), negative_slope=0.2)

        self.severity_score = self.severity_head(self.z)
        self.gan_fake = self.latent_gan(self.z)
        self.gan_real = self.latent_gan(torch.randn_like(self.z))

        z_spatial = F.relu(self.decoder_fc(self.z))
        z_spatial = z_spatial.view(-1, *self.encoder_feature_shape)
        out = TensorBase(z_spatial)
        orig_x = TensorBase(torch.zeros_like(self.input_image))

        for layer in self.unet.layers[1:]:
            out.orig = orig_x
            nres = layer(out)
            out.orig = None
            if hasattr(nres, "orig"):
                nres.orig = None
            out = nres

        self.decoder_output = out
        return self.severity_score


def graft_xaae_encoder(
    encoder: nn.Module,
    input_size: int = 256,
    input_channels: int = 3,
    encoding_dims: int = 128,
    severity_outputs: int = 1,
    severity_head: nn.Module | None = None,
    gen_train: bool = True,
    skip_dropout: float = 1.0,
    freeze_encoder: bool = False,
) -> EncoderGraftedAAE:
    """Build xAAEnet around a user encoder."""
    return EncoderGraftedAAE(
        encoder=encoder,
        input_size=input_size,
        input_channels=input_channels,
        encoding_dims=encoding_dims,
        severity_outputs=severity_outputs,
        severity_head=severity_head,
        gen_train=gen_train,
        skip_dropout=skip_dropout,
        freeze_encoder=freeze_encoder,
    )
