"""Add the logic that lets a developer provide a classifier and connect it to the AAE model."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_graft_classifier.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/03_graft_classifier.ipynb #f689aa4f
# TODO: write the classifier grafting functions here
