"""Écris ici la logique permettant à un développeur de fournir son classifieur et de le brancher au modèle AAE."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_graft_classifier.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/03_graft_classifier.ipynb #f689aa4f
# TODO: écrire ici les fonctions de greffe du classifieur
