"""xAAEnet is a fastai adversarial autoencoder composed of an encoder, a latent space, a discriminator, a classifier, and a decoder."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_model_aae.ipynb.

# %% auto #0
__all__ = ['AAE', 'UnetBlock', 'ResizeToOrig', 'DynamicUnetSkipDropout', 'default_device']

# %% ../nbs/01_model_aae.ipynb #299b7d0d
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from torch import Tensor
from fastai.vision.all import *
from fastai.callback.hook import *
from fastai.torch_core import TensorBase
from pytorch_msssim import ms_ssim


def _module_device(module: nn.Module) -> torch.device:
    try:
        return next(module.parameters()).device
    except StopIteration:
        return torch.device("cpu")

# %% ../nbs/01_model_aae.ipynb #a938d613
class AAE(nn.Module):
    """Adversarial autoencoder used by xAAEnet.

    The model encodes an image into a latent vector `z`, predicts class logits
    from this latent space, regularizes the latent distribution with an
    adversarial discriminator, and reconstructs the input image with a U-Net
    decoder.

    Parameters
    ----------
    input_size : int, default=256
        Spatial size of the square input images.
    input_channels : int, default=3
        Number of input image channels.
    encoding_dims : int, default=128
        Dimension of the latent representation `z`.
    classes : int, default=2
        Number of output classes for the classifier head (must be 2; binary only).
    gen_train : bool, default=True
        Whether the adversarial step trains the generator side of the AAE.
    skip_dropout : float, default=1
        Dropout probability applied on decoder skip connections.
    """

    def __init__(
        self,
        input_size=256,
        input_channels=3,
        encoding_dims=128,
        classes=2, 
        gen_train=True,
        skip_dropout=1 # Replaces skip_weight with skip_dropout
    ):
        super(AAE, self).__init__()
        assert classes == 2, (
            "tell_me_why supports binary image classification only; classes must be 2."
        )

        self.gen_train = gen_train
        self.count_acc = 1
        self.classes = classes
        self.input_size = input_size
        self.input_channels = input_channels
        self.encoding_dims = encoding_dims
        
        # A. Base encoder
        encoder_base = nn.Sequential(*list(resnet34(weights=ResNet34_Weights.DEFAULT).children())[:-2])
        
        # Instantiate the new U-Net architecture.
        self.unet = DynamicUnetSkipDropout(
            encoder=encoder_base, 
            n_out=input_channels, 
            img_size=(input_size, input_size), 
            skip_dropout=skip_dropout,
            last_cross=False # Crucial: disables the source-image residual connection at the output
        )
        
        # B. xAI bottleneck (feature map size depends on input_size)
        self.flatten = nn.Flatten()
        self.encoder_feature_shape = self._infer_encoder_feature_shape()
        flat_features = int(torch.tensor(self.encoder_feature_shape).prod().item())
        
        self.fc_encode = nn.Linear(flat_features, encoding_dims)
        self.bn_lin = nn.BatchNorm1d(num_features=encoding_dims)
        self.decoder_fc = nn.Linear(encoding_dims, flat_features)

        # C. Network heads
        self.dropout = nn.Dropout(p=0.2)
        self.linear = nn.Linear(encoding_dims, self.classes, bias=True) 

        self.fc_crit1 = nn.Linear(encoding_dims, 64)
        self.fc_crit2 = nn.Linear(64, 16)
        self.fc_crit3 = nn.Linear(16, 1)

        self.bn_crit1 = nn.BatchNorm1d(num_features=64)
        self.bn_crit2 = nn.BatchNorm1d(num_features=16)

    def _infer_encoder_feature_shape(self) -> tuple[int, ...]:
        encoder = self.unet.layers[0]
        was_training = encoder.training
        device = _module_device(encoder)
        try:
            encoder.eval()
            with torch.no_grad():
                sample = torch.zeros(1, self.input_channels, self.input_size, self.input_size, device=device)
                features = encoder(sample)
        finally:
            encoder.train(was_training)
        return tuple(features.shape[1:])

    def latent_gan(self, zi: Tensor) -> Tensor:
        # Discriminator MLP without batch norm on hidden layers (matches colleague experiments).
        x = F.leaky_relu(self.fc_crit1(zi), negative_slope=0.2)
        x = F.leaky_relu(self.fc_crit2(x), negative_slope=0.2)
        x = torch.sigmoid(self.fc_crit3(x))
        return x

    def aae_loss_func(self, output, target):
        alpha = 0.84
    
        adversarial_loss = nn.BCELoss()
        if self.gen_train: 
            valid = torch.ones_like(self.gan_fake, requires_grad=False).detach()
            self.adv_loss = adversarial_loss(self.gan_fake, valid)
            self.crit_loss = 0
        else:
            valid = torch.ones_like(self.gan_real, requires_grad=False).detach()
            fake = torch.zeros_like(self.gan_fake, requires_grad=False).detach()
            self.real_loss = adversarial_loss(self.gan_real, valid)
            self.fake_loss = adversarial_loss(self.gan_fake, fake)
            self.adv_loss = 0.6 * self.real_loss + 0.4 * self.fake_loss
            self.crit_loss = self.adv_loss

        loss = self.adv_loss
            
        return loss

    def denoising_ae_loss_func(self, clean_xb,RECONS_WEIGHT,ADV_WEIGHT, pred, yb):
        # pred et yb sont ignorés car cette fonction est dédiée au pré-entraînement de l'AE en mode débruitage
        # Fastai attend une signature de fonction de perte avec ces arguments, même si on ne les utilise pas tous
        #Partie loss recon
        alpha = 0.84
        l1_loss = F.l1_loss(self.decoder_output, clean_xb)
        ms_ssim_val = ms_ssim(self.decoder_output, clean_xb, data_range=1.0, size_average=True)
        msssim_loss = 1.0 - ms_ssim_val
        self.recons_loss = alpha * msssim_loss + (1.0 - alpha) * l1_loss
        #partie loss adversarial
        adversarial_loss = nn.BCELoss()
        if self.gen_train: 
            valid = torch.ones_like(self.gan_fake, requires_grad=False).detach()
            self.adv_loss = adversarial_loss(self.gan_fake, valid)
            self.crit_loss = 0
        else:
            valid = torch.ones_like(self.gan_real, requires_grad=False).detach()
            fake = torch.zeros_like(self.gan_fake, requires_grad=False).detach()
            self.real_loss = adversarial_loss(self.gan_real, valid)
            self.fake_loss = adversarial_loss(self.gan_fake, fake)
            self.adv_loss = 0.6 * self.real_loss + 0.4 * self.fake_loss
            self.crit_loss = self.adv_loss
        self.recons_loss = RECONS_WEIGHT* self.recons_loss + ADV_WEIGHT*self.adv_loss
        
        return self.recons_loss 

    def classif_loss_func(self, output, target,ADV_WEIGHT, RECONS_WEIGHT, CLASS_WEIGHT, **kwargs):
        alpha = 0.84
        # On utilise self.input_image car il n'y a pas de corruption ici
        l1_loss = F.l1_loss(self.decoder_output, self.input_image)
        ms_ssim_val = ms_ssim(self.decoder_output, self.input_image, data_range=1.0, size_average=True)
        msssim_loss = 1.0 - ms_ssim_val
        self.recons_loss = alpha * msssim_loss + (1.0 - alpha) * l1_loss

        # LOn sauvegarde l'attribut pour LossAttrMetric
        self.classif_loss = F.cross_entropy(output, target, **kwargs)
        #partie loss adversarial
        adversarial_loss = nn.BCELoss()
        if self.gen_train: 
            valid = torch.ones_like(self.gan_fake, requires_grad=False).detach()
            self.adv_loss = adversarial_loss(self.gan_fake, valid)
            self.crit_loss = 0
        else:
            valid = torch.ones_like(self.gan_real, requires_grad=False).detach()
            fake = torch.zeros_like(self.gan_fake, requires_grad=False).detach()
            self.real_loss = adversarial_loss(self.gan_real, valid)
            self.fake_loss = adversarial_loss(self.gan_fake, fake)
            self.adv_loss = 0.6 * self.real_loss + 0.4 * self.fake_loss
            self.crit_loss = self.adv_loss

        loss = ADV_WEIGHT * self.adv_loss + RECONS_WEIGHT * self.recons_loss + CLASS_WEIGHT * self.classif_loss
        return loss

    def pure_classif_loss_func(self, pred, target, **kwargs):
        return F.cross_entropy(pred, target, **kwargs)

    def forward(self, x):
        self.input_image = x

        # =========================================================
        # STEP 1: ENCODER
        # =========================================================
        # Silently triggers skip-connection storage (self.unet.sfs).
        feats = self.unet.layers[0](x)

        # =========================================================
        # STEP 2: AAE BOTTLENECK
        # =========================================================
        flat = self.flatten(feats)
        self.z = self.fc_encode(flat)

        labels = self.linear(self.z)

        self.gan_fake = self.latent_gan(self.z)
        z_random = torch.randn_like(self.z)
        self.gan_real = self.latent_gan(z_random)

        # =========================================================
        # STEP 3: DECODER
        # =========================================================
        z_spatial = F.relu(self.decoder_fc(self.z))
        z_spatial = z_spatial.view(-1, *self.encoder_feature_shape) 
        
        out = TensorBase(z_spatial)
        
        # Keep a ghost tensor for compatibility with ResizeToOrig.
        ghost_shape = torch.zeros_like(self.input_image)
        orig_x = TensorBase(ghost_shape)
        
        # Run the decoder, including the standard fastai bottleneck and UnetBlocks.
        for layer in self.unet.layers[1:]:
            out.orig = orig_x
            nres = layer(out)
            
            # Clean up VRAM.
            out.orig = None
            if hasattr(nres, 'orig'):
                nres.orig = None
                
            out = nres
            
        self.decoder_output = out

        return labels

# %% ../nbs/01_model_aae.ipynb #7ac53c2b
def _get_sz_change_idxs(sizes):
    """Identify indices where the encoder feature-map spatial size changes."""
    feature_szs = []
    for size in sizes:
        # Walk through each size tuple (C, H, W) and keep the spatial dimension.
        W = size[-1]
        feature_szs.append(W)
    return list(np.where(np.array(feature_szs[:-1]) != np.array(feature_szs[1:]))[0])

class UnetBlock(Module):
    @delegates(ConvLayer.__init__)
    def __init__(self, up_in_c, x_in_c, hook,
                 final_div=True, blur=False,
                 act_cls=defaults.activation,
                 self_attention=False,
                 init=nn.init.kaiming_normal_,
                 norm_type=None,
                 skip_dropout=0.0,
                 **kwargs):

        self.hook = hook

        # Upsampling
        self.shuf = PixelShuffle_ICNR(
            up_in_c, up_in_c//2,
            blur=blur,
            act_cls=act_cls,
            norm_type=norm_type
        )

        self.bn = BatchNorm(x_in_c)

        # 2D spatial dropout applied only to the skip connection.
        self.skip_dropout = nn.Dropout2d(skip_dropout) if skip_dropout > 0 else None

        ni = up_in_c//2 + x_in_c
        nf = ni if final_div else ni//2

        self.conv1 = ConvLayer(ni, nf, act_cls=act_cls, norm_type=norm_type, **kwargs)
        self.conv2 = ConvLayer(
            nf, nf,
            act_cls=act_cls,
            norm_type=norm_type,
            xtra=SelfAttention(nf) if self_attention else None,
            **kwargs
        )

        self.relu = act_cls()
        apply_init(nn.Sequential(self.conv1, self.conv2), init)

    def forward(self, up_in):
        s = self.hook.stored  # Retrieve encoder features.
        up_out = self.shuf(up_in)

        # Align spatial dimensions if needed.
        if s.shape[-2:] != up_out.shape[-2:]:
            up_out = F.interpolate(up_out, s.shape[-2:], mode='nearest')

        s = self.bn(s)

        # Apply dropout to the skip-connection spatial channels.
        if self.skip_dropout is not None:
            s = self.skip_dropout(s)

        cat_x = self.relu(torch.cat([up_out, s], dim=1))
        return self.conv2(self.conv1(cat_x))

class ResizeToOrig(Module):
    """Resize the tensor to the original image size stored in the .orig attribute."""
    def __init__(self, mode='nearest'):
        self.mode = mode

    def forward(self, x):
        if x.orig.shape[-2:] != x.shape[-2:]:
            x = F.interpolate(x, x.orig.shape[-2:], mode=self.mode)
        return x

class DynamicUnetSkipDropout(SequentialEx):
    """Dynamic U-Net with Dropout2d on skip connections."""
    def __init__(self, encoder, n_out, img_size,
                 blur=False, blur_final=True,
                 self_attention=False,
                 y_range=None,
                 last_cross=True,
                 bottle=False,
                 act_cls=defaults.activation,
                 init=nn.init.kaiming_normal_,
                 norm_type=None,
                 skip_dropout=0.0,
                 **kwargs):

        imsize = img_size
        sizes = model_sizes(encoder, size=imsize)
        sz_chg_idxs = list(reversed(_get_sz_change_idxs(sizes)))

        # Initialize hooks on the encoder.
        self.sfs = hook_outputs([encoder[i] for i in sz_chg_idxs], detach=False)

        x = dummy_eval(encoder, imsize).detach()
        ni = sizes[-1][1]

        # Standard U-Net bottleneck.
        middle_conv = nn.Sequential(
            ConvLayer(ni, ni*2, act_cls=act_cls, norm_type=norm_type, **kwargs),
            ConvLayer(ni*2, ni, act_cls=act_cls, norm_type=norm_type, **kwargs)
        ).eval()

        x = middle_conv(x)
        layers = [encoder, BatchNorm(ni), nn.ReLU(), middle_conv]

        # Build the decoder.
        for i, idx in enumerate(sz_chg_idxs):
            not_final = i != len(sz_chg_idxs)-1

            up_in_c = int(x.shape[1])
            x_in_c  = int(sizes[idx][1])

            do_blur = blur and (not_final or blur_final)
            sa = self_attention and (i == len(sz_chg_idxs)-3)

            unet_block = UnetBlock(
                up_in_c, x_in_c, self.sfs[i],
                final_div=not_final,
                blur=do_blur,
                self_attention=sa,
                act_cls=act_cls,
                init=init,
                norm_type=norm_type,
                skip_dropout=skip_dropout,
                **kwargs
            ).eval()

            layers.append(unet_block)
            x = unet_block(x)

        ni = x.shape[1]

        if imsize != sizes[0][-2:]:
            layers.append(PixelShuffle_ICNR(ni, act_cls=act_cls, norm_type=norm_type))

        layers.append(ResizeToOrig())

        if last_cross:
            layers.append(MergeLayer(dense=True))
            ni += in_channels(encoder)
            layers.append(
                ResBlock(
                    1, ni, ni//2 if bottle else ni,
                    act_cls=act_cls, norm_type=norm_type, **kwargs
                )
            )

        layers += [ConvLayer(ni, n_out, ks=1, act_cls=None, norm_type=norm_type, **kwargs)]
        apply_init(nn.Sequential(layers[3], layers[-2]), init)

        if y_range is not None:
            layers.append(SigmoidRange(*y_range))

        layers.append(ToTensorBase())
        super().__init__(*layers)

    def __del__(self):
        if hasattr(self, "sfs"):
            self.sfs.remove()

# %% ../nbs/01_model_aae.ipynb #6ceb263e
def default_device():
    """Return the best available PyTorch device: CUDA, MPS, then CPU."""
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")
