"""Add the functions that display the Gaussian latent space and feature figures."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_visualization.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/05_visualization.ipynb #a20fbafe
# TODO: write the visualization functions to export here
