"""Écris ici les fonctions pour afficher l'espace latent gaussien et les figures de features."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_visualization.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/04_visualization.ipynb #a20fbafe
# TODO: écrire ici les fonctions de visualisation à exporter
