"""Relate the latent classification axis to interpretable image feature scores."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_visualization.ipynb.

# %% ../nbs/05_visualization.ipynb #6779418c
from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
from sklearn.cross_decomposition import PLSRegression
from sklearn.preprocessing import StandardScaler

DEFAULT_FEATURE_SCORE_COLUMNS: tuple[str, ...] = (
    "brightness",
    "variance",
    "skewness",
    "color_covariance_red_blue",
    "redness_dominance",
    "symmetry_error",
    "top_bottom_brightness_ratio",
    "center_texture",
    "eye_region_contrast",
    "jaw_texture",
    "fft_high_frequency_ratio",
)


# %% auto #0
__all__ = ['DEFAULT_FEATURE_SCORE_COLUMNS', 'run_pls_feature_figures']

# %% ../nbs/05_visualization.ipynb #fb6e5c1d
def pearson_r2_signed(x: np.ndarray, y: np.ndarray) -> float:
    r, _ = stats.pearsonr(np.asarray(x).ravel(), np.asarray(y).ravel())
    return float(np.sign(r) * r**2)


def supervised_pls_latent(
    z: np.ndarray,
    target_score: np.ndarray,
    *,
    n_components: int = 2,
) -> tuple[np.ndarray, PLSRegression, float, float]:
    z = np.asarray(z, dtype=np.float64)
    y = np.asarray(target_score, dtype=np.float64).reshape(-1, 1)
    pls = PLSRegression(n_components=n_components)
    pls.fit(z, y)
    z_pls = pls.transform(z)
    r2_c1 = stats.pearsonr(z_pls[:, 0], y.ravel())[0] ** 2
    r2_c2 = stats.pearsonr(z_pls[:, 1], y.ravel())[0] ** 2 if n_components > 1 else float("nan")
    return z_pls, pls, float(r2_c1), float(r2_c2)


def compute_pls_feature_alignment(
    pls_c1: np.ndarray,
    pls_c2: np.ndarray,
    features_z: np.ndarray,
    feature_names: Sequence[str],
) -> dict[str, dict[str, Any]]:
    pls_c1 = np.asarray(pls_c1).ravel()
    pls_c2 = np.asarray(pls_c2).ravel()
    out: dict[str, dict[str, Any]] = {}
    for j, name in enumerate(feature_names):
        vals = features_z[:, j]
        r_x, _ = stats.pearsonr(pls_c1, vals)
        r_y, _ = stats.pearsonr(pls_c2, vals)
        _, _, r_reg, p_reg, _ = stats.linregress(pls_c1, vals)
        out[name] = {
            "vector_xy": (float(r_x), float(r_y)),
            "r2_signed": pearson_r2_signed(pls_c1, vals),
            "p_value": float(p_reg),
            "linregress_r": float(r_reg),
        }
    return out


def _standardize_features(features: np.ndarray) -> np.ndarray:
    return StandardScaler().fit_transform(np.asarray(features, dtype=np.float64))


# %% ../nbs/05_visualization.ipynb #cf1b01a7
def plot_feature_alignment_panels(
    pls_c1: np.ndarray,
    features_z: np.ndarray,
    feature_names: Sequence[str],
    alignment: dict[str, dict[str, Any]],
    *,
    mask_positive: np.ndarray | None = None,
    positive_label: str = "positive",
    negative_label: str = "negative",
    cols: int = 3,
    title: str | None = None,
    show: bool = True,
) -> plt.Figure:
    """Grid of scatter plots: PLS component 1 vs each standardized feature score."""
    pls_c1 = np.asarray(pls_c1).ravel()
    n_feat = len(feature_names)
    rows = int(np.ceil(n_feat / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 5, rows * 4.5))
    fig.patch.set_facecolor("#0e1117")
    axes_flat = np.atleast_1d(axes).flatten()

    if mask_positive is None:
        mask_positive = np.ones(len(pls_c1), dtype=bool)
    mask_negative = ~mask_positive

    def pval_str(p: float) -> str:
        if p < 0.001:
            return "p < 0.001"
        if p < 0.01:
            return "p < 0.01"
        if p < 0.05:
            return "p < 0.05"
        return f"p = {p:.3f}"

    for i, feat in enumerate(feature_names):
        ax = axes_flat[i]
        ax.set_facecolor("#0d1117")
        vals = features_z[:, i]
        ax.scatter(
            pls_c1[mask_negative],
            vals[mask_negative],
            c="#444c56",
            s=6,
            alpha=0.4,
            linewidths=0,
            label=negative_label,
            zorder=1,
        )
        ax.scatter(
            pls_c1[mask_positive],
            vals[mask_positive],
            c="#63b3ed",
            s=8,
            alpha=0.6,
            linewidths=0,
            label=positive_label,
            zorder=2,
        )
        xr = np.linspace(pls_c1.min(), pls_c1.max(), 200)
        m, b, r_reg, p_reg, _ = stats.linregress(pls_c1, vals)
        ax.plot(xr, m * xr + b, color="#56de91", lw=2.0, alpha=0.9, zorder=3, label=f"r = {r_reg:.2f} (all)")

        r2_signed = alignment[feat]["r2_signed"]
        r2_col = "#56de91" if r2_signed >= 0 else "#fc6e6e"
        r2_sign = "▲" if r2_signed >= 0 else "▼"
        ax.set_title(feat, fontsize=11, fontweight="bold", pad=6, color="#c9d1d9")
        ax.set_xlabel("PLS component 1", fontsize=8, color="#8b949e")
        ax.set_ylabel(feat, fontsize=8, color="#8b949e")
        ax.text(
            0.03,
            0.97,
            f"|r²| = {abs(r2_signed):.3f}  |  {pval_str(p_reg)}",
            transform=ax.transAxes,
            fontsize=8,
            va="top",
            ha="left",
            color="#c9d1d9",
            bbox=dict(boxstyle="round,pad=0.35", fc="#1c2128", ec="#30363d", alpha=0.85),
        )
        ax.text(
            0.97,
            0.05,
            f"{r2_sign} signed r² = {r2_signed:+.3f}",
            transform=ax.transAxes,
            fontsize=8.5,
            fontweight="bold",
            va="bottom",
            ha="right",
            color=r2_col,
        )
        ax.legend(loc="lower right", fontsize=7, framealpha=0.3)
        ax.grid(True, alpha=0.12)
        ax.tick_params(colors="#8b949e")
        for spine in ax.spines.values():
            spine.set_edgecolor("#30363d")

    for j in range(i + 1, len(axes_flat)):
        axes_flat[j].set_visible(False)

    fig.suptitle(
        title or "Feature alignment vs PLS component 1\n(▲ positive signed r²  |  ▼ negative)",
        y=1.01,
        fontsize=12,
        fontweight="bold",
        color="#c9d1d9",
    )
    fig.tight_layout()
    if show:
        plt.show()
    return fig


# %% ../nbs/05_visualization.ipynb #a49ac9d8
def plot_feature_importance_ranking(
    importance_rank: Sequence[str],
    alignment: dict[str, dict[str, Any]],
    *,
    target_label: str = "target",
    show: bool = True,
) -> plt.Figure:
    """Horizontal bar chart of signed r² vs PLS1, sorted by |r²|."""
    import matplotlib.patches as mpatches

    r2_vals = np.array([alignment[f]["r2_signed"] for f in importance_rank])
    colors = ["#56de91" if v >= 0 else "#fc6e6e" for v in r2_vals]
    fig, ax = plt.subplots(figsize=(11, 5))
    fig.patch.set_facecolor("#0e1117")
    ax.set_facecolor("#0d1117")
    ax.barh(list(importance_rank), r2_vals, color=colors, height=0.55, edgecolor="#21262d", linewidth=0.6)
    ax.axvline(0, color="#8b949e", lw=1.2)
    ax.set_xlabel(
        f"Signed r² (full sample)  →  positive = increases with PLS 1 toward '{target_label}'",
        fontsize=10,
        color="#c9d1d9",
    )
    ax.set_title(
        f"Feature importance ranking — PLS axis '{target_label}'",
        fontweight="bold",
        pad=10,
        loc="left",
        color="white",
    )
    ax.tick_params(colors="#8b949e")
    for spine in ax.spines.values():
        spine.set_edgecolor("#30363d")
    ax.grid(True, axis="x", alpha=0.15)
    ax.legend(
        handles=[
            mpatches.Patch(color="#56de91", label=f"Aligned with PLS 1 (→ {target_label})"),
            mpatches.Patch(color="#fc6e6e", label="Anti-aligned with PLS 1"),
        ],
        loc="lower right",
        framealpha=0.3,
    )
    fig.tight_layout()
    if show:
        plt.show()
    return fig


# %% ../nbs/05_visualization.ipynb #f34cca34
def run_pls_feature_figures(
    z: np.ndarray,
    target_score: np.ndarray,
    feature_table,
    *,
    feature_columns: Sequence[str] | None = None,
    target_label: str = "target",
    mask_positive: np.ndarray | None = None,
    positive_label: str = "positive",
    negative_label: str = "negative",
    save_dir: str | Path | None = None,
    show: bool = True,
) -> dict[str, Any]:
    """Build alignment panels and importance ranking; display and optionally save PNGs."""
    feature_columns = list(feature_columns or DEFAULT_FEATURE_SCORE_COLUMNS)
    features_z = _standardize_features(feature_table[feature_columns].values)
    z_pls, pls, r2_c1, r2_c2 = supervised_pls_latent(z, target_score)
    pls_c1, pls_c2 = z_pls[:, 0], z_pls[:, 1]
    alignment = compute_pls_feature_alignment(pls_c1, pls_c2, features_z, feature_columns)
    importance_rank = sorted(feature_columns, key=lambda f: abs(alignment[f]["r2_signed"]), reverse=True)
    alignment_fig = plot_feature_alignment_panels(
        pls_c1, features_z, feature_columns, alignment,
        mask_positive=mask_positive, positive_label=positive_label, negative_label=negative_label, show=show,
    )
    importance_fig = plot_feature_importance_ranking(importance_rank, alignment, target_label=target_label, show=show)
    if save_dir is not None:
        save_dir = Path(save_dir)
        save_dir.mkdir(parents=True, exist_ok=True)
        alignment_fig.savefig(save_dir / "feature_alignment_panels.png", dpi=150, bbox_inches="tight", facecolor=alignment_fig.get_facecolor())
        importance_fig.savefig(save_dir / "feature_importance_ranking.png", dpi=150, bbox_inches="tight", facecolor=importance_fig.get_facecolor())
    return {
        "alignment_fig": alignment_fig,
        "importance_fig": importance_fig,
        "importance_rank": importance_rank,
        "alignment": alignment,
    }

